# -*- coding: utf-8 -*-
"""PostLab 10 11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wTak2X5jiFr2MUOeXM3ZyFKhJF2CvPbb
"""

import kagglehub
path = kagglehub.dataset_download("mlg-ulb/creditcardfraud")

import kagglehub
path = kagglehub.dataset_download("fedesoriano/the-boston-houseprice-data")

import kagglehub
path = kagglehub.dataset_download("imakash3011/customer-personality-analysis")

import pandas as pd
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score


df = pd.read_csv("/kaggle/input/creditcardfraud/creditcard.csv")
print(df.head())
print(df['Class'].value_counts())

X = df.drop('Class', axis=1)
y = df['Class']

smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

scaler = StandardScaler()
X_resampled['Amount'] = scaler.fit_transform(X_resampled[['Amount']])
X_resampled['Time'] = scaler.fit_transform(X_resampled[['Time']])

X_train, X_test, y_train, y_test = train_test_split(
    X_resampled, y_resampled,
    test_size=0.3, random_state=42
)

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)


rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

def evaluate(y_test, y_pred, model_name):
    print(f"\n{model_name}")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Precision:", precision_score(y_test, y_pred))
    print("Recall:", recall_score(y_test, y_pred))
    print("F1-score:", f1_score(y_test, y_pred))


evaluate(y_test, y_pred_lr, "Logistic Regression")
evaluate(y_test, y_pred_rf, "Random Forest")

# Best model Random Forest

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

df = pd.read_csv("/kaggle/input/the-boston-houseprice-data/boston.csv")
print(df.head())
print(df.info())

print(df.isnull().sum()) #there are no null values but if there were null do the following below
df.fillna(df.mean(numeric_only=True), inplace=True)
df.fillna(df.mode().iloc[0], inplace=True)

scaler = StandardScaler()

X = df.drop('MEDV', axis=1)
y = df['MEDV']

X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.3,
    random_state=42
)

lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)

dt = DecisionTreeRegressor(random_state=42)
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)


def evaluate(y_test, y_pred, model_name):
    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))

    print(f"\n{model_name}")
    print("MAE:", mae)
    print("RMSE:", rmse)

evaluate(y_test, y_pred_lr, "Linear Regression")
evaluate(y_test, y_pred_dt, "Decision Tree")

comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted_LR": y_pred_lr,
    "Predicted_DT": y_pred_dt
})

print(comparison.head())

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/kaggle/input/customer-personality-analysis/marketing_campaign.csv", sep='\t')
print(df.head())

features = [
    'Income', 'Recency',
    'MntWines', 'MntFruits', 'MntMeatProducts',
    'MntFishProducts', 'MntSweetProducts', 'MntGoldProds',
    'NumWebPurchases', 'NumCatalogPurchases', 'NumStorePurchases',
    'NumWebVisitsMonth'
]

data = df[features]
print(data.isnull().sum())

# Fill missing Income with median
data['Income'].fillna(data['Income'].median(), inplace=True)


scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

inertia = []

for k in range(2, 11):
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(scaled_data)
    inertia.append(kmeans.inertia_)

plt.plot(range(2, 11), inertia, marker='o')
plt.xlabel("Number of Clusters (K)")
plt.ylabel("Inertia")
plt.title("Elbow Method")
plt.show()

kmeans = KMeans(n_clusters=4, random_state=42)
clusters = kmeans.fit_predict(scaled_data)

data['Cluster'] = clusters

cluster_summary = data.groupby('Cluster').mean()
print(cluster_summary)